esphome:
  name: air-quality-v1-rev1
  friendly_name: air-quality-v1-rev1

esp32:
  board: m5stack-stamps3
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ov+ZTQRno6I1VPUM//8Q1f6KM5M+oB5sRs+7xEDvdho="

ota:
  - platform: esphome
    password: "4c11f42c9b708b4e61ff4621ef659bed"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality-V1-Rev1"
    password: "mECQXJuWaVL6"

captive_portal:
    
packages:
  - !include common/air-quality-v1-rev1-base.yaml