esphome:
  name: unit-poe-cam-w-v1-rev1
  friendly_name: M5Stack Unit POE CAM V1.1

esp32:
  variant: esp32
  flash_size: 16MB
  framework:
    type: esp-idf

psram:
  mode: quad
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome



# Wi-Fi or Ethernet, you can only enable one of it
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "unit-poe-cam-w-v1-rev1"
#     password: ""

ethernet:
  type: W5500
  clk_pin: GPIO23
  mosi_pin: GPIO13
  miso_pin: GPIO38
  cs_pin: GPIO4
  clock_speed: 20MHz


i2c:
  - id: cam_i2c
    sda: GPIO14
    scl: GPIO12


esp32_camera:
  name: "OV3660 Camera"
  i2c_id: cam_i2c
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  data_pins: [ GPIO32, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19 ]
  vsync_pin: GPIO22 
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15


binary_sensor:
  - platform: gpio
    name: "Button"
    pin:
      number: GPIO37
      inverted: true

output:
  - platform: ledc
    pin:
      number: GPIO0
      inverted: true
    id: status_led

light:
  - platform: monochromatic
    output: status_led
    name: "Status LED"
    id: sled
    restore_mode: RESTORE_DEFAULT_ON