esphome:
  name: atom-socket
  friendly_name: M5Stack Atom Socket
  name_add_mac_suffix: true
  project:
    name: m5stack.atom-socket
    version: 2026.3.0

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ap:

captive_portal:

improv_serial:

esp32_improv:
  authorizer: none

uart:
  rx_pin: GPIO22
  baud_rate: 4800
  parity: EVEN

switch:
  - platform: gpio
    name: "Atom Sokcet"
    pin:
      number: GPIO23
      inverted: False
    restore_mode: ALWAYS_ON

sensor:
  - platform: hlw8032
    voltage:
      name: HLW8032 Voltage
      id: hlw8032_voltage
    current:
      name: HLW8032 Current
      id: hlw8032_current
    power:
      name: HLW8032 Power
      id: hlw8032_power
    apparent_power:
      name: HLW8032 Apparent Power
      id: hlw8032_apparent_power
    power_factor:
      name: HLW8032 Power Factor
      id: hlw8032_power_factor

